name: flutter_bloc_lyrics
description: Flutter BLoC example

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  equatable: ^0.2.0
  http: ^0.12.0
  bloc: ^1.0.0
  flutter_bloc: ^1.0.0
  flutter_webview_plugin: ^0.3.7
  easy_localization: ^1.3.1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  uses-material-design: true
  assets:
    - "lib/resources/langs/en-US.json"
